#!/bin/bash

INFILE="$1"
OUTFILE="${2:-${INFILE%.*}.pdf}"
CLASS=lettre

if [ -z $OUTFILE ]; then
  echo "Usage: $0 <recipient_file.<md|rst>> <outfile.<tex|pdf>>"
  exit 1
fi

pandoc \
  --template lettre.latex \
  --latex-engine=lualatex \
  -V "lang=french" \
  -o "$OUTFILE" "$INFILE"

