#!/bin/bash

INFILE="$1"
OUTFILE="${2:-${INFILE%.*}.pdf}"

if [ -z $OUTFILE ]; then
  echo "Usage: $0 <recipient_file.<md|rst>> <outfile.<tex|pdf>>"
  exit 1
fi

pandoc \
  --template $(dirname $0)/lettre.latex \
  --pdf-engine=lualatex \
  -V "lang=fr-FR" \
  -o "$OUTFILE" "$INFILE"

